/**************************************************************************************
Copyright 2015 Applied Research Associates, Inc.
Licensed under the Apache License, Version 2.0 (the License); you may not use
this file except in compliance with the License. You may obtain a copy of the License
at:
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under

the License is distributed on an AS IS BASIS, WITHOUT WARRANTIES OR
CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
**************************************************************************************/
#pragma once

#include <pybind11/pybind11.h>

namespace py = pybind11;

void define_pybSECompartment(py::module_& m);
void define_pybSECompartmentManager(py::module_& m);
void define_pybPhysiologyEngineTrack(py::module_& m);
void define_pybSEAcuteRespiratoryDistress(py::module_& m);
void define_pybSEAcuteStress(py::module_& m);
void define_pybSEAirwayObstruction(py::module_& m);
void define_pybSEApnea(py::module_& m);
void define_pybSEAsthmaAttack(py::module_& m);
void define_pybSEBrainInjury(py::module_& m);
void define_pybSEBreathHold(py::module_& m);
void define_pybSEBronchoconstriction(py::module_& m);
void define_pybSEBurnWound(py::module_& m);
void define_pybSECardiacArrest(py::module_& m);
void define_pybSEChestCompression(py::module_& m);
void define_pybSEChestCompressionForce(py::module_& m);
void define_pybSEChestCompressionForceScale(py::module_& m);
void define_pybSEChestOcclusiveDressing(py::module_& m);
void define_pybSEConsciousRespiration(py::module_& m);
void define_pybSEConsumeNutrients(py::module_& m);
void define_pybSEExercise(py::module_& m);
void define_pybSEForcedExhale(py::module_& m);
void define_pybSEForcedInhale(py::module_& m);
void define_pybSEHemmorrhage(py::module_& m);
void define_pybSEInfection(py::module_& m);
void define_pybSEIntubation(py::module_& m);
void define_pybSEMechanicalVentilation(py::module_& m);
void define_pybSENeedleDecompression(py::module_& m);
void define_pybSEOverride(py::module_& m);
void define_pybSEPainStimulus(py::module_& m);
void define_pybSEPatientAction(py::module_& m);
void define_pybSEPatientAssessmentRequest(py::module_& m);
void define_pybSEPericardialEffusion(py::module_& m);
void define_pybSEPupillaryResponse(py::module_& m);
void define_pybSESleep(py::module_& m);
void define_pybSESubstanceBolus(py::module_& m);
void define_pybSESubstanceCompoundInfusion(py::module_& m);
void define_pybSESubstanceAdministration(py::module_& m);
void define_pybSESubstanceInfusion(py::module_& m);
void define_pybSESubstanceNasalDose(py::module_& m);
void define_pybSESubstanceOralDose(py::module_& m);
void define_pybSETensionPneumothroax(py::module_& m);
void define_pybSETourniquet(py::module_& m);
void define_pybSEUrinate(py::module_& m);
void define_pybSEUseInhaler(py::module_& m);
void define_pybSECompleteBloodCount(py::module_& m);
void define_pybSEComprehensiveMetabolicPanel(py::module_& m);
void define_pybSEPulmonaryFunctionTest(py::module_& m);
void define_pybSESequentialOrganFailureAssessment(py::module_& m);
void define_pybSEUrinalysis(py::module_& m);
void define_pybSEUrinalysisMicroscopic(py::module_& m);
void define_pybSEChronicAnemia(py::module_& m);
void define_pybSEChronicObstructivePulmonaryDisease(py::module_& m);
void define_pybSEChronicPericardialEffusion(py::module_& m);
void define_pybSEChronicRenalStenosis(py::module_& m);
void define_pybSEChronicVentricularSystolicDysfunction(py::module_& m);
void define_pybSEDehydration(py::module_& m);
void define_pybSEDiabetesType1(py::module_& m);
void define_pybSEDiabetesType2(py::module_& m);
void define_pybSEImpairedAlveolarExchange(py::module_& m);
void define_pybSELobarPneumonia(py::module_& m);
void define_pybSEStarvation(py::module_& m);
void define_pybSENutrition(py::module_& m);
void define_pybSEPatient(py::module_& m);
void define_pybSEProperty(py::module_& m);
void define_pybSEScalar(py::module_& m);
void define_pybSEScalar0To1(py::module_& m);
void define_pybSEScalarAmount(py::module_& m);
void define_pybSEScalarAmountPerMass(py::module_& m);
void define_pybSEScalarAmountPerTime(py::module_& m);
void define_pybSEScalarAmountPerVolume(py::module_& m);
void define_pybSEScalarArea(py::module_& m);
void define_pybSEScalarAreaPerTimePressure(py::module_& m);
void define_pybSEScalarElectricCapacitance(py::module_& m);
void define_pybSEScalarElectricCharge(py::module_& m);
void define_pybSEScalarElectricCurrent(py::module_& m);
void define_pybSEScalarElectricInductance(py::module_& m);
void define_pybSEScalarElectricPotential(py::module_& m);
void define_pybSEScalarElectricResistance(py::module_& m);
void define_pybSEScalarEnergy(py::module_& m);
void define_pybSEScalarEnergyPerAmount(py::module_& m);
void define_pybSEScalarEnergyPerMass(py::module_& m);
void define_pybSEScalarFlowCompliance(py::module_& m);
void define_pybSEScalarFlowElastance(py::module_& m);
void define_pybSEScalarFlowInertance(py::module_& m);
void define_pybSEScalarFlowResistance(py::module_& m);
void define_pybSEScalarForce(py::module_& m);
void define_pybSEScalarFraction(py::module_& m);
void define_pybSEScalarFrequency(py::module_& m);
void define_pybSEScalarHeatCapacitance(py::module_& m);
void define_pybSEScalarHeatCapacitancePerAmount(py::module_& m);
void define_pybSEScalarHeatCapacitancePerMass(py::module_& m);
void define_pybSEScalarHeatConductance(py::module_& m);
void define_pybSEScalarHeatConductancePerArea(py::module_& m);
void define_pybSEScalarHeatInductance(py::module_& m);
void define_pybSEScalarHeatResistance(py::module_& m);
void define_pybSEScalarHeatResistanceArea(py::module_& m);
void define_pybSEScalarInversePressure(py::module_& m);
void define_pybSEScalarInverseVolume(py::module_& m);
void define_pybSEScalarLength(py::module_& m);
void define_pybSEScalarLengthPerTime(py::module_& m);
void define_pybSEScalarLengthPerTimePressure(py::module_& m);
void define_pybSEScalarMass(py::module_& m);
void define_pybSEScalarMassPerAmount(py::module_& m);
void define_pybSEScalarMassPerAreaTime(py::module_& m);
void define_pybSEScalarMassPerMass(py::module_& m);
void define_pybSEScalarMassPerTime(py::module_& m);
void define_pybSEScalarMassPerVolume(py::module_& m);
void define_pybSEScalarNeg1To1(py::module_& m);
void define_pybSEScalarOsmolality(py::module_& m);
void define_pybSEScalarOsmolarity(py::module_& m);
void define_pybSEScalarPower(py::module_& m);
void define_pybSEScalarPowerPerAreaTemperatureToTheFourth(py::module_& m);
void define_pybSEScalarPressure(py::module_& m);
void define_pybSEScalarPressurePerVolume(py::module_& m);
void define_pybSEScalarPressureTimePerArea(py::module_& m);
void define_pybSEScalarPressureTimePerVolumeArea(py::module_& m);
void define_pybSEScalarTemperature(py::module_& m);
void define_pybSEScalarTime(py::module_& m);
void define_pybSEScalarTimeMassPerVolume(py::module_& m);
void define_pybSEScalarVolume(py::module_& m);
void define_pybSEScalarVolumePerPressure(py::module_& m);
void define_pybSEScalarVolumePerTime(py::module_& m);
void define_pybSEScalarVolumePerTimeArea(py::module_& m);
void define_pybSEScalarVolumePerTimeMass(py::module_& m);
void define_pybSEScalarVolumePerTimePressure(py::module_& m);
void define_pybSEScalarVolumePerTimePressureArea(py::module_& m);
void define_pybSEAction(py::module_& m);
void define_pybSEActionManager(py::module_& m);
void define_pybSEAdvanceTime(py::module_& m);
void define_pybSEAnesthesiaMachineActionCollection(py::module_& m);
void define_pybSEConditionManager(py::module_& m);
void define_pybSEEnvironmentActionCollection(py::module_& m);
void define_pybSEInhalerActionCollection(py::module_& m);
void define_pybSEPatientActionCollection(py::module_& m);
void define_pybSEScenario(py::module_& m);
void define_pybSEScenarioAutoSerialization(py::module_& m);
void define_pybSEScenarioExec(py::module_& m);
void define_pybSEScenarioInitialParameters(py::module_& m);
void define_pybSESerializeState(py::module_& m);
void define_pybSECompartmentDataRequest(py::module_& m);
void define_pybSECompartmentSubstanceDataRequest(py::module_& m);
void define_pybSEDataRequest(py::module_& m);
void define_pybSEDataRequestManager(py::module_& m);
void define_pybSEEnvironmentDataRequest(py::module_& m);
void define_pybSEEquipmentDataRequest(py::module_& m);
void define_pybSEGasCompartmentDataRequest(py::module_& m);
void define_pybSELiquidCompartmentDataRequest(py::module_& m);
void define_pybSEPatientDataRequest(py::module_& m);
void define_pybSEPhysiologyDataRequest(py::module_& m);
void define_pybSESubstanceDataRequest(py::module_& m);
void define_pybSEThermalCompartmentDataRequest(py::module_& m);
void define_pybSETissueCompartmentDataRequest(py::module_& m);
void define_pybSESubstance(py::module_& m);
void define_pybSESubstanceAerosolization(py::module_& m);
void define_pybSESubstanceClearance(py::module_& m);
void define_pybSESubstanceCompound(py::module_& m);
void define_pybSESubstanceConcentration(py::module_& m);
void define_pybSESubstanceFraction(py::module_& m);
void define_pybSESubstanceManager(py::module_& m);
void define_pybSESubstancePharmacodynamics(py::module_& m);
void define_pybSESubstancePharmacokinetics(py::module_& m);
void define_pybSESubstancePhysicochemicals(py::module_& m);
void define_pybSESubstanceTissuePharmacokinetics(py::module_& m);
void define_pybSEBloodChemistrySystem(py::module_& m);
void define_pybSECardiovascularSystem(py::module_& m);
void define_pybSEDrugSystem(py::module_& m);
void define_pybSEEndocrineSystem(py::module_& m);
void define_pybSEEnergySystem(py::module_& m);
void define_pybSEGastrointestinalSystem(py::module_& m);
void define_pybSEHepaticSystem(py::module_& m);
void define_pybSENervousSystem(py::module_& m);
void define_pybSERenalSystem(py::module_& m);
void define_pybSERespiratorySystem(py::module_& m);
void define_pybSETissueSystem(py::module_& m);
void define_pybSESystem(py::module_& m);
void define_pybLogger(py::module_& m);
void define_pybLoggable(py::module_& m);
void define_pybBioGearsEngine(py::module_& m);
void define_pybBioGearsEngineHeader(py::module_& m);
void define_pybSEScalar(py::module_& m);
void define_pybcardio(py::module_& m);
void define_pybscalarpressure(py::module_& m);

PYBIND11_MODULE(pybiogears, m)
{
  //!Order of these function matters :(
  //I plan to come back and create a block level
  //Inheritance tree to represent why they are in a given order

  define_pybLogger(m);
  define_pybLoggable(m);
  {
    define_pybSEPatientAction(m);
    {
      define_pybSEAcuteRespiratoryDistress(m);
      //define_pybSEAcuteStress(m);
      //define_pybSEAirwayObstruction(m);
      //define_pybSEApnea(m);
      //define_pybSEAsthmaAttack(m);
      //define_pybSEBrainInjury(m);
      //define_pybSEBreathHold(m);
      //define_pybSEBronchoconstriction(m);
      //define_pybSEBurnWound(m);
      //define_pybSECardiacArrest(m);
      //define_pybSEChestCompression(m);
      //define_pybSEChestCompressionForce(m);
      //define_pybSEChestCompressionForceScale(m);
      //define_pybSEChestOcclusiveDressing(m);
      //define_pybSEConsciousRespiration(m);
      //define_pybSEConsumeNutrients(m);
      //define_pybSEExercise(m);
      //define_pybSEForcedExhale(m);
      //define_pybSEForcedInhale(m);
      //define_pybSEHemmorrhage(m);
      //define_pybSEInfection(m);
      //define_pybSEIntubation(m);
      //define_pybSEMechanicalVentilation(m);
      //define_pybSENeedleDecompression(m);
      //define_pybSEOverride(m);
      //define_pybSEPainStimulus(m);
      //define_pybSEPatientAssessmentRequest(m);
      //define_pybSEPericardialEffusion(m);
      //define_pybSEPupillaryResponse(m);
      //define_pybSESleep(m);
      //define_pybSESubstanceAdministration(m);
      //define_pybSESubstanceInfusion(m);
      //define_pybSESubstanceCompoundInfusion(m);
      //define_pybSESubstanceBolus(m);
      //define_pybSESubstanceNasalDose(m);
      //define_pybSESubstanceOralDose(m);
      //define_pybSETensionPneumothroax(m);
      //define_pybSETourniquet(m);
      //define_pybSEUrinate(m);
      //define_pybSEUseInhaler(m);
      //define_pybSECompleteBloodCount(m);
      //define_pybSEComprehensiveMetabolicPanel(m);
      //define_pybSEPulmonaryFunctionTest(m);
      //define_pybSESequentialOrganFailureAssessment(m);
      //define_pybSEUrinalysis(m);
      //define_pybSEUrinalysisMicroscopic(m);
      //define_pybSEChronicAnemia(m);
      //define_pybSEChronicObstructivePulmonaryDisease(m);
      //define_pybSEChronicPericardialEffusion(m);
      //define_pybSEChronicRenalStenosis(m);
      //define_pybSEChronicVentricularSystolicDysfunction(m);
      //define_pybSEDehydration(m);
      //define_pybSEDiabetesType1(m);
      //define_pybSEDiabetesType2(m);
      //define_pybSEImpairedAlveolarExchange(m);
      //define_pybSELobarPneumonia(m);
      //define_pybSEStarvation(m);
      //define_pybSENutrition(m);
    }
    define_pybSEProperty(m);
    {
      define_pybSEScalar(m);
      {
        define_pybSEScalar0To1(m);
        //define_pybSEScalarAmount(m);
        //define_pybSEScalarAmountPerMass(m);
        //define_pybSEScalarAmountPerTime(m);
        //define_pybSEScalarAmountPerVolume(m);
        //define_pybSEScalarArea(m);
        //define_pybSEScalarAreaPerTimePressure(m);
        //define_pybSEScalarElectricCapacitance(m);
        //define_pybSEScalarElectricCharge(m);
        //define_pybSEScalarElectricCurrent(m);
        //define_pybSEScalarElectricInductance(m);
        //define_pybSEScalarElectricPotential(m);
        //define_pybSEScalarElectricResistance(m);
        //define_pybSEScalarEnergy(m);
        //define_pybSEScalarEnergyPerAmount(m);
        //define_pybSEScalarEnergyPerMass(m);
        //define_pybSEScalarFlowCompliance(m);
        //define_pybSEScalarFlowElastance(m);
        //define_pybSEScalarFlowInertance(m);
        //define_pybSEScalarFlowResistance(m);
        //define_pybSEScalarForce(m);
        //define_pybSEScalarFraction(m);
        //define_pybSEScalarFrequency(m);
        //define_pybSEScalarHeatCapacitance(m);
        //define_pybSEScalarHeatCapacitancePerAmount(m);
        //define_pybSEScalarHeatCapacitancePerMass(m);
        //define_pybSEScalarHeatConductance(m);
        //define_pybSEScalarHeatConductancePerArea(m);
        //define_pybSEScalarHeatInductance(m);
        //define_pybSEScalarHeatResistance(m);
        //define_pybSEScalarHeatResistanceArea(m);
        //define_pybSEScalarInversePressure(m);
        //define_pybSEScalarInverseVolume(m);
        //define_pybSEScalarLength(m);
        //define_pybSEScalarLengthPerTime(m);
        //define_pybSEScalarLengthPerTimePressure(m);
        //define_pybSEScalarMass(m);
        //define_pybSEScalarMassPerAmount(m);
        //define_pybSEScalarMassPerAreaTime(m);
        //define_pybSEScalarMassPerMass(m);
        //define_pybSEScalarMassPerTime(m);
        //define_pybSEScalarMassPerVolume(m);
        //define_pybSEScalarNeg1To1(m);
        //define_pybSEScalarOsmolality(m);
        //define_pybSEScalarOsmolarity(m);
        //define_pybSEScalarPower(m);
        //define_pybSEScalarPowerPerAreaTemperatureToTheFourth(m);
        //define_pybSEScalarPressure(m);
        //define_pybSEScalarPressurePerVolume(m);
        //define_pybSEScalarPressureTimePerArea(m);
        //define_pybSEScalarPressureTimePerVolumeArea(m);
        //define_pybSEScalarTemperature(m);
        //define_pybSEScalarTime(m);
        //define_pybSEScalarTimeMassPerVolume(m);
        //define_pybSEScalarVolume(m);
        //define_pybSEScalarVolumePerPressure(m);
        //define_pybSEScalarVolumePerTime(m);
        //define_pybSEScalarVolumePerTimeArea(m);
        //define_pybSEScalarVolumePerTimeMass(m);
        //define_pybSEScalarVolumePerTimePressure(m);
        //define_pybSEScalarVolumePerTimePressureArea(m);
      }
    }
  }

  //define_pybSECompartment(m);
  //define_pybSECompartmentManager(m);
  //define_pybPhysiologyEngineTrack(m);

  //define_pybSEPatient(m);

  //define_pybSEScalar0To1(m);
  //define_pybSEAction(m);
  //define_pybSEActionManager(m);
  //define_pybSEAdvanceTime(m);
  //define_pybSEAnesthesiaMachineActionCollection(m);
  //define_pybSEConditionManager(m);
  //define_pybSEEnvironmentActionCollection(m);
  //define_pybSEInhalerActionCollection(m);
  //define_pybSEPatientActionCollection(m);
  //define_pybSEScenario(m);
  //define_pybSEScenarioAutoSerialization(m);
  //define_pybSEScenarioExec(m);
  //define_pybSEScenarioInitialParameters(m);
  //define_pybSESerializeState(m);
  //define_pybSECompartmentDataRequest(m);
  //define_pybSECompartmentSubstanceDataRequest(m);
  //define_pybSEDataRequest(m);
  //define_pybSEDataRequestManager(m);
  //define_pybSEEnvironmentDataRequest(m);
  //define_pybSEEquipmentDataRequest(m);
  //define_pybSEGasCompartmentDataRequest(m);
  //define_pybSELiquidCompartmentDataRequest(m);
  //define_pybSEPatientDataRequest(m);
  //define_pybSEPhysiologyDataRequest(m);
  //define_pybSESubstanceDataRequest(m);
  //define_pybSEThermalCompartmentDataRequest(m);
  //define_pybSETissueCompartmentDataRequest(m);
  //define_pybSESubstance(m);
  //define_pybSESubstanceAerosolization(m);
  //define_pybSESubstanceClearance(m);
  //define_pybSESubstanceCompound(m);
  //define_pybSESubstanceConcentration(m);
  //define_pybSESubstanceFraction(m);
  //define_pybSESubstanceManager(m);
  //define_pybSESubstancePharmacodynamics(m);
  //define_pybSESubstancePharmacokinetics(m);
  //define_pybSESubstancePhysicochemicals(m);
  //define_pybSESubstanceTissuePharmacokinetics(m);
  //define_pybSEBloodChemistrySystem(m);
  //define_pybSECardiovascularSystem(m);
  //define_pybSEDrugSystem(m);
  //define_pybSEEndocrineSystem(m);
  //define_pybSEEnergySystem(m);
  //define_pybSEGastrointestinalSystem(m);
  //define_pybSEHepaticSystem(m);
  //define_pybSENervousSystem(m);
  //define_pybSERenalSystem(m);
  //define_pybSERespiratorySystem(m);
  //define_pybSETissueSystem(m);
  //define_pybSESystem(m);
  //define_pybBioGearsEngine(m);
  //define_pybBioGearsEngineHeader(m);
  //define_pybSEScalar(m);
  //define_pybcardio(m);
  //define_pybscalarpressure(m);
}