cmake_minimum_required(VERSION 3.8.0)
cmake_policy(VERSION 3.8.0)

  set( CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY_${CONFIG}} )
  set( CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY_${CONFIG}} )
  set( CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY_${CONFIG}} )
  if( EXISTS "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/unittest${CONFIG_SUFFIX}${CMAKE_EXECUTABLE_SUFFIX}" )
    fixup_bundle("${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/unittest${CONFIG_SUFFIX}${CMAKE_EXECUTABLE_SUFFIX}"
                 ""
                 "${THIRD_PARTY_LIB};${THIRD_PARTY_BIN}"
    )
  endif()
