
%{
#include <biogears/cdm/scenario/requests/SEGasCompartmentDataRequest.h>
%}

%include <biogears/exports.h>

%import <biogears/container/Tree.swg>
%import <biogears/cdm/utils/Logger.swg>
%import <biogears/cdm/CommonDataModel.swg>

%include <std_map.i>

%import <biogears/cdm/scenario/requests/SEDataRequest.swg>

%nspace biogears::SEGasCompartmentDataRequest;

%include <biogears/cdm/scenario/requests/SEGasCompartmentDataRequest.h>
