
%{
#include <biogears/cdm/scenario/requests/SEPhysiologyDataRequest.h>
%}

%include <biogears/exports.h>

%import <biogears/container/Tree.swg>
%import <biogears/cdm/utils/Logger.swg>
%import <biogears/cdm/CommonDataModel.swg>

%import <std_map.i>

%import <biogears/cdm/scenario/requests/SEDataRequest.swg>

%nspace BIOGEARS_NAMESPACE SEPhysiologyDataRequest;

%include <biogears/cdm/scenario/requests/SEPhysiologyDataRequest.h>
