// Add necessary symbols to generated header
%{
#include<biogears/cdm/system/equipment/Inhaler/actions/SEInhalerConfiguration.h>
%}

%include <biogears/exports.h>

%import <biogears/cdm/utils/Logger.swg>
%import <biogears/cdm/CommonDataModel.swg>
%import <biogears/container/Tree.swg>


%import <biogears/cdm/substance/SESubstance.swg>
%import <biogears/cdm/substance/SESubstanceManager.swg>

%import <biogears/cdm/system/equipment/Inhaler/SEInhaler.swg>

%include <biogears/cdm/system/equipment/Inhaler/actions/SEInhalerConfiguration.h>
